### PR TITLE
:sparkles: Corrected bug and added some useful arguments

### PR DESCRIPTION
**Pull request by rdenise**
Corrected bug if database files were not present (now using wget thought python). It also now install the files in a hidden folder at the users home directory. 

Added argument to give output folder, and the database files. 

Corrected bug for creation of some fasta files and localisation of database files. And change how to check the blastdb files in case the analysis is done in the same folder but the merge fasta file is changed.

Corrected bug for phages known, the Class, Family, Genus... were not correct in some case. Switch from a position of the column to directly a dict that have the columns of the dataframe as key (as it was done for some other conditions).

Modify the saving of the heatmap to be proportional of the number of data. And added parameters to have a editable file in pdf and svg.

### CODE REVIEW

**Comment by tsp-kucbd** [comment]
Thank you @rdenise , we adapted a few of your suggestions.

**Comment by rdenise** [comment]
I see that you added some of the changes I did.

You should also do the change for the phage assignation because of two of the 4 cases because at the moment the columns does not match the real informations and so it is false (I saw that when I tested the script with a genome that exists in the ICTV database).

original

```python
ic(f"{matching_species_row}")
list_of_S_data = matching_species_row[0:].values.flatten().tolist()
ic(f"{list_of_S_data[14:20]}")
ic(f"{list_of_S_data}")
print_res(f"""Query sequence is: 
        Class:{list_of_S_data[14]}
        Family: {list_of_S_data[15]}
        Subfamily:{list_of_S_data[16]}
        Genus:{list_of_S_data[17]}
        Species:{list_of_S_data[19]}
```

my modification

```python
ic(matching_species_row)
list_of_S_data = matching_species_row.iloc[0].to_dict()
ic(list_of_S_data)
print_res(f"""\nQuery sequence is: 
        Class: {list_of_S_data["Class"]}
        Family: {list_of_S_data["Family"]}
        Subfamily: {list_of_S_data["Subfamily"]}
        Genus: {list_of_S_data["Genus"]}
        Species: {list_of_S_data["Species"]}
         """)
```

You already to exactly like that for the two other cases

Best
Remi

**Comment by amillard** [comment]
being consistent would make out code better- i will do this. Can you let me know of the accessions you tested as I don`t get the same error using currently classified phages as you have gottten

**Comment by rdenise** [comment]
Here the one I tested and for which the annotation was not good: MN929097

If I remember correctly it said that the Class was Not Define Yet which is false because the class is Caudoviricetes. Because the number of column of Class is 11 not 14 in the table. That is why using the column name instead of the number is more efficient here (as it is done by you in other condition of the if/else)

**Comment by amillard** [comment]
Thanks , columns names are used in all cases now.  
MN929097 would come up as Not Defined Yet...  although it is reported on NCBI as class Caudoviricetes . It hasn`t been classified by ICTV , which is the taxonomy we use. So will be reported as No Defined Yet . thanks for the help on the being consistent on referring to df names and not numbers

**Pull request closed without merging**
